"""Install a GitHub Actions workflow that lints the repository on every push / pull request."""

from __future__ import annotations

from pathlib import Path

WORKFLOW = """\
# Generated by ansible-lint-kit (alk ci-setup). Lints Ansible content on every push and pull request.
name: Ansible lint

on:
  push:
  pull_request:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install ansible-core, ansible-lint, yamllint and alk
        run: pip install "ansible-core{core_spec}" ansible-lint yamllint "git+https://github.com/eaglionxxo/ansible-lint-kit.git"
      - name: Install collections and roles (requirements.yml)
        run: alk deps .
      - name: Lint, migration scan and syntax check
        run: alk check . --no-fix --report alk-report.md
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: alk-report
          path: alk-report.md
"""


def setup(project: Path, core_version: str = "", force: bool = False) -> tuple[Path, bool]:
    """Write .github/workflows/ansible-lint.yml. Returns (path, written)."""
    target = project.resolve() / ".github" / "workflows" / "ansible-lint.yml"
    if target.exists() and not force:
        return target, False
    target.parent.mkdir(parents=True, exist_ok=True)
    spec = f"=={core_version}.*" if core_version else ""
    target.write_text(WORKFLOW.format(core_spec=spec), encoding="utf-8")
    return target, True
